apiVersion: v2
name: goqueue
description: A production-grade message queue built in Go
type: application
version: 0.1.0
appVersion: "0.2.0"
keywords:
  - message-queue
  - go
  - kafka-alternative
home: https://github.com/abd-ulbasit/goqueue
sources:
  - https://github.com/abd-ulbasit/goqueue
maintainers:
  - name: basit
    email: abd-ulbasit@example.com
